sudo: true

language: python
python:
        - "2.6"
        - "2.7"
        - "pypy"

before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"

install:
        - "sudo apt-get install cx-freeze"
        - "pip install cx-freeze"
        - "pip install pytest"
        - "pip install future"

script:
        - py.test --verbose -m "not fail_travis"

notifications:
        - email: false
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
