#sudo: false

language: python
python:
        - "2.6"
        - "2.7"
        - "pypy"

before_install:
        # Required for importing tkinter...
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start" 


install:
        # remove for container api
        - "pip install cx-freeze"
        - "pip install pytest pytest-cov"
        - "pip install future"

#before_script:
        # socket already in use error when run by our test_esky.py script
#        - python -m SimpleHTTPServer 8000 &

script:
        - sudo py.test 

after_script:
        - kill `ps aux | grep "python -m SimpleHTTPServer" | grep -v grep | awk '{print $2}'`


notifications:
        - email: false
#
#
#
#
#
#
#
#
#
