#sudo: false

language: python
python:
        - "2.6"
        - "2.7"
        - "pypy"

install:
        # remove for container api when cx-freeze gets approved
        - "sudo apt-get install cx-freeze"
        - "pip install future"
#        - "pip install bbfreeze"

before_script:
        # socket already in use error when run by our test_esky.py script
        - python -m SimpleHTTPServer 8000 &

script:
        - sudo python -m pytest --verbose --pastebin=all

after_script:
        - kill `ps aux | grep "python -m SimpleHTTPServer" | grep -v grep | awk '{print $2}'`


notifications:
        - email: false


someshit
