sudo: true

language: python
python:
        - "2.6"
        - "2.7"
        - "pypy"

install:
        - "pip install cx-freeze"
        - "pip install pytest pytest-cov"
        - "pip install future"

script:
        - py.test --verbose -m not "skip_travis"

notifications:
        - email: false
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
